<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!-- 1. Cài đặt các gói thư viện EF Core bắt buộc -->
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <!-- 2. Kết nối tới Project Domain (để nhìn thấy User, Ticket...) -->
  <ItemGroup>
    <ProjectReference Include="..\TicketSystem.Domain\TicketSystem.Domain.csproj" />
    <ProjectReference Include="..\TicketSystem.Application\TicketSystem.Application.csproj" />
  </ItemGroup>

</Project>